Vagrant.configure("2") do |config|                      #Specify the version of the object “config”;​

    os = "generic/rocky9"
    host_net = "192.168.100"
    config.vm.synced_folder '.', '/vagrant', disabled: true

    my_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8SO8OZHhBNPXcMTEMYZ7hNrpmHHcLSmmUCdjRDiPenISR/vOMHCoMaRBFuHYviJrwJXAM5rqGbrLcPm9XgoA3Tw4oKdPjekbvmWOuLB5vo9OM8AP7HUwws7HiyPVXV3f7TupZV6zUbr/GSQaIVkabJm89HVNp3zn68+LqJQs5mVJ+PryCCk5tdj1hiCeQVbcqx750p4RQt+tD9qx6RlGb62oLs4LH3VboBbeU2v0cpXvSvMXKNKWGhumKKw/o8hj+ARp+Zpvd0z52RRGKu6Ut3TCT8sEY69xMCTLUZPlutUtwcfNKEWbolWw0Nkio2Dez5JUqjnUwNb/zkYQqExKigJHnRSTZY16W7zbuZCGFMnVikj4SyjD4fnbg02vbfLHJBCGntdg/iaC3QuS7JQchjJiAJfuEIJrvFjYO1T/wvhGA4pUEYMY9rNHvF+LJ5b9St42k3nr12qwQisPiDmZG4AzsGCugkBzRyyjZ0bxShoir3acN9u26qJyE1sQfXis= alexa@DESKTOP-ELFODJV
"
	
	#Configurare FiiPractic-App
	
	config.vm.define :app do |app_config|               #Define the VM object;​
        app_config.vm.provider "virtualbox" do |vb|     #Specify which provider should be used;​
            vb.memory = "2048"
            vb.cpus = 2                                 #Specify the properties of the VM;​
            vb.name = "FiiPractic-App"
        end
        app_config.vm.host_name = 'app.fiipractic.lan'
        app_config.vm.box = "#{os}"
        app_config.vm.network "private_network", ip: "#{host_net}.10"
        app_config.vm.provision "shell", inline: <<-SHELL
            mkdir -p /root/.ssh 
            echo "#{my_key}" > /root/.ssh/authorized_keys
            chmod 700 /root/.ssh
            chmod 600 /root/.ssh/authorized_keys
            echo "root:fiipractic" | chpasswd
            echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/99-vagrant.conf
            echo "PermitRootLogin yes" >> /etc/ssh/sshd_config.d/99-vagrant.conf
            systemctl restart sshd
            yum install -y git
            yum install -y wget
            yum install -y vim
        SHELL
    end
	
	#Configurare FiiPractic-GitLab
	
	config.vm.define :gitlab do |gitlab_config|
        gitlab_config.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = 4
            vb.name = "FiiPractic-GitLab"
        end
        gitlab_config.vm.host_name = 'gitlab.fiipractic.lan'
        gitlab_config.vm.box = "#{os}"
        gitlab_config.vm.network "private_network", ip: "#{host_net}.20"
        gitlab_config.vm.disk :disk, size: "20GB", primary: true
        gitlab_config.vm.provision "shell", inline: <<-SHELL
            mkdir -p /root/.ssh 
            echo "#{my_key}" > /root/.ssh/authorized_keys
            chmod 700 /root/.ssh
            chmod 600 /root/.ssh/authorized_keys
            echo "root:fiipractic" | chpasswd
            echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/99-vagrant.conf
            echo "PermitRootLogin yes" >> /etc/ssh/sshd_config.d/99-vagrant.conf
            systemctl restart sshd
            yum install -y git
            yum install -y wget
            yum install -y vim
        SHELL
    end

end


